# Generated by Django 4.2.1 on 2023-06-20 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Coun', models.CharField(max_length=100)),
                ('capti', models.CharField(max_length=100)),
            ],
        ),
    ]
