# Generated by Django 4.2.1 on 2023-06-20 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capi', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='country',
            old_name='Coun',
            new_name='country_name',
        ),
        migrations.RemoveField(
            model_name='country',
            name='capti',
        ),
        migrations.RemoveField(
            model_name='country',
            name='id',
        ),
        migrations.AddField(
            model_name='country',
            name='capital_name',
            field=models.OneToOneField(default=False, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.capital'),
        ),
    ]
